services:
  backend:
    # image: python:3.13.4-slim-bullseye
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment: 
      - PORT=8000
      - MY_PROJECT=Hello World
    env_file:
      - .env
    volumes:
      - ./backend/src:/app
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        - action: sync+restart
          path: backend/src/
          target: /app
  db_service:
    image: postgres:17.5
    ports:
      - 55432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=mydb
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data

volumes:
  dc_managed_db_volume: